"""Tests for the faithful, small-sample SMC++ building blocks."""

import itertools

import numpy as np
import pytest
from scipy.linalg import expm

from watchgen.mini_smcpp import (
    composite_log_likelihood,
    conditioned_sfs,
    constant_csc_transition_matrix,
    cross_population_survival,
    emission_probabilities,
    expected_first_coalescence,
    forward_log_likelihood,
    incorporate_theta,
    interval_conditioned_sfs,
    pair_interval_probabilities,
    two_locus_kernel,
)

BREAKS = np.array([0.0, 0.25, 0.75, 2.0, np.inf])


class TestCoalescentUnits:
    def test_pair_mean_is_2N_generations(self):
        assert expected_first_coalescence(2, 10_000) == 20_000

    def test_first_event_rate_for_many_lineages(self):
        assert expected_first_coalescence(20, 10_000) == pytest.approx(20_000 / 190)

    @pytest.mark.parametrize("n,N", [(1, 1), (2, 0), (2, np.inf)])
    def test_invalid_inputs(self, n, N):
        with pytest.raises(ValueError):
            expected_first_coalescence(n, N)


class TestConditionedSFS:
    def test_two_sample_closed_form(self):
        # With no undistinguished samples, the only finite branches are the
        # two distinguished tips, each of length tau.
        tau = 1.7
        expected = np.zeros((3, 1))
        expected[1, 0] = 2 * tau
        np.testing.assert_allclose(conditioned_sfs(tau, 0), expected)

    def test_tau_zero_merges_distinguished_pair_immediately(self):
        csfs = conditioned_sfs(0.0, 1)
        assert csfs[1].sum() == pytest.approx(0.0, abs=1e-12)
        assert csfs[2, 0] > 0
        assert csfs[0, 1] > 0

    def test_shape_nonnegative_and_no_fixed_branch(self):
        for n in range(5):
            csfs = conditioned_sfs(0.8, n)
            assert csfs.shape == (3, n + 1)
            assert np.all(csfs >= 0)
            assert csfs[0, 0] == 0
            assert csfs[2, n] == 0

    def test_population_scale_multiplies_branch_lengths(self):
        # Scaling both the conditioned time and N by c scales every branch by c.
        base = conditioned_sfs(0.7, 2, relative_size=1.0)
        scaled = conditioned_sfs(2.1, 2, relative_size=3.0)
        np.testing.assert_allclose(scaled, 3 * base, rtol=1e-10, atol=1e-10)

    def test_invalid_inputs(self):
        for args in [(-1, 1, 1), (1, -1, 1), (1, 1, 0)]:
            with pytest.raises(ValueError):
                conditioned_sfs(*args)


class TestMutationTransform:
    def test_matches_original_source_formula(self):
        csfs = conditioned_sfs(1.0, 2)
        theta = 0.03
        p = incorporate_theta(csfs, theta)
        L = csfs.sum()
        factor = -np.expm1(-theta * L) / L
        expected = csfs * factor
        expected[0, 0] = 1 - expected.sum()
        np.testing.assert_allclose(p, expected)

    def test_is_probability_distribution(self):
        for tau in [0, 0.1, 1, 5]:
            p = incorporate_theta(conditioned_sfs(tau, 3), 0.01)
            assert np.all(p >= 0)
            assert p.sum() == pytest.approx(1.0)

    def test_larger_theta_reduces_monomorphic_probability(self):
        csfs = conditioned_sfs(1.0, 2)
        assert incorporate_theta(csfs, 0.1)[0, 0] < incorporate_theta(csfs, 0.01)[0, 0]


class TestIntervalAveraging:
    def test_stationary_interval_probabilities(self):
        pi = pair_interval_probabilities(BREAKS)
        expected = np.exp(-BREAKS[:-1]) - np.r_[np.exp(-BREAKS[1:-1]), 0.0]
        np.testing.assert_allclose(pi, expected)
        assert pi.sum() == pytest.approx(1.0)

    def test_two_sample_interval_csfs_has_known_mean(self):
        csfs = interval_conditioned_sfs(BREAKS, 0, quadrature_order=16)
        rate = 1.0
        for k, (lo, hi) in enumerate(itertools.pairwise(BREAKS)):
            if np.isinf(hi):
                mean = lo + 1 / rate
            else:
                width = hi - lo
                mean = lo + 1 / rate - width / np.expm1(rate * width)
            assert csfs[k, 1, 0] == pytest.approx(2 * mean, rel=1e-10)

    def test_interval_emissions_normalize(self):
        emissions = emission_probabilities(BREAKS, 2, 0.02, quadrature_order=8)
        np.testing.assert_allclose(emissions.sum(axis=(1, 2)), 1.0)

    @pytest.mark.parametrize("n", [-1, 1.5])
    def test_invalid_undistinguished_sample_count(self, n):
        with pytest.raises(ValueError, match="n_undistinguished"):
            interval_conditioned_sfs(BREAKS, n)

    def test_matches_original_cpp_conditioned_sfs(self):
        # Generated by the unmodified upstream conditioned_sfs.cpp at commit
        # 6779faec, for n=2 and the BREAKS discretization used in this file.
        upstream = np.array(
            [
                [
                    [0, 1.2520273820951933, 0.27154154941640973],
                    [0.2074952467937346, 0.029493193390618455, 0.0026057277217473931],
                    [0.46015250661804236, 0.66991594861994097, 0],
                ],
                [
                    [0, 1.0507445517901803, 0.17421776761032737],
                    [0.65873642800331711, 0.24185297444573237, 0.057916515014152278],
                    [0.17149879454621941, 0.45536258492923154, 0],
                ],
                [
                    [0, 0.86712874466271928, 0.11733123770928562],
                    [1.2775018098547104, 0.83932736397675634, 0.379293029936001],
                    [0.035760578505782868, 0.13206128315101534, 0],
                ],
                [
                    [0, 0.80406913308794625, 0.1010180399374826],
                    [2.3769467881861472, 2.2400012106647935, 1.3830520011490586],
                    [0.0020375932059572689, 0.0081352395139082465, 0],
                ],
            ]
        )
        np.testing.assert_allclose(
            interval_conditioned_sfs(BREAKS, 2, quadrature_order=32),
            upstream,
            rtol=2e-12,
            atol=2e-12,
        )


class TestTwoLocusKernel:
    def test_matches_matrix_exponential_of_source_generator(self):
        duration, coal_rate, rho = 1.3, 0.7, 0.2
        generator = np.array(
            [[-rho, rho, 0.0], [coal_rate, -2 * coal_rate, coal_rate], [0, 0, 0]]
        )
        np.testing.assert_allclose(
            two_locus_kernel(duration, coal_rate, rho),
            expm(duration * generator),
            rtol=1e-13,
            atol=1e-13,
        )

    def test_stochastic_and_absorbing(self):
        kernel = two_locus_kernel(2.0, 1.0, 0.1)
        assert np.all(kernel >= 0)
        np.testing.assert_allclose(kernel.sum(axis=1), 1.0)
        np.testing.assert_array_equal(kernel[2], [0, 0, 1])

    def test_no_recombination_never_leaves_linked_state(self):
        np.testing.assert_array_equal(two_locus_kernel(10, 1, 0)[0], [1, 0, 0])


class TestDiscretizedTransition:
    def test_rows_are_probability_distributions(self):
        P = constant_csc_transition_matrix(BREAKS, 1.0, 0.1)
        assert np.all(P >= 0)
        np.testing.assert_allclose(P.sum(axis=1), 1.0)

    def test_zero_recombination_is_identity(self):
        np.testing.assert_allclose(
            constant_csc_transition_matrix(BREAKS, 1.0, 0.0), np.eye(len(BREAKS) - 1)
        )

    def test_transition_does_not_depend_on_undistinguished_sample_count(self):
        # Sample size is absent from the API by design: extra samples affect
        # CSFS emissions, not the distinguished pair's transition process.
        P = constant_csc_transition_matrix(BREAKS, 1.0, 0.1)
        assert P.shape == (4, 4)

    def test_matches_original_cpp_transition_matrix(self):
        # Generated by upstream transition.cpp at commit 6779faec. Production
        # SMC++ mixes in beta=1e-5 uniformly over its five time boundaries;
        # undo that stabilizer because this teaching implementation omits it.
        upstream_regularized = np.array(
            [
                [
                    0.99174529246296617,
                    0.0032468265741395557,
                    0.0035708180737013995,
                    0.0014350628891928771,
                ],
                [
                    0.0026436261133923051,
                    0.979094191031328,
                    0.013027698894885299,
                    0.0052324839603943938,
                ],
                [
                    0.0026436261133923051,
                    0.015019266270524353,
                    0.96997636130338538,
                    0.012358746312697949,
                ],
                [
                    0.0026436261133923051,
                    0.015019266270524353,
                    0.053560572100880742,
                    0.92877453551520261,
                ],
            ]
        )
        beta = 1e-5
        upstream = (upstream_regularized - beta / len(BREAKS)) / (1 - beta)
        np.testing.assert_allclose(
            constant_csc_transition_matrix(BREAKS, 1.0, 0.1),
            upstream,
            rtol=2e-13,
            atol=2e-13,
        )


class TestLikelihood:
    @pytest.fixture
    def model(self):
        emissions = emission_probabilities(BREAKS, 2, 0.02, quadrature_order=8)
        transitions = constant_csc_transition_matrix(BREAKS, 1.0, 0.1)
        initial = pair_interval_probabilities(BREAKS)
        return transitions, emissions, initial

    def test_scaled_forward_matches_brute_force(self, model):
        transitions, emissions, initial = model
        observations = np.array([[0, 0], [1, 0], [0, 1]])
        alpha = initial * emissions[:, 0, 0]
        alpha = (alpha @ transitions) * emissions[:, 1, 0]
        alpha = (alpha @ transitions) * emissions[:, 0, 1]
        expected = np.log(alpha.sum())
        assert forward_log_likelihood(
            observations, transitions, emissions, initial
        ) == pytest.approx(expected)

    def test_missing_observation_has_unit_emission(self, model):
        transitions, emissions, initial = model
        data = np.array([[0, 0], [-1, -1], [1, 0]])
        without_missing = np.array([[0, 0], [1, 0]])
        # A missing site still advances the Markov chain once.
        P2 = transitions @ transitions
        assert forward_log_likelihood(
            data, transitions, emissions, initial
        ) == pytest.approx(
            forward_log_likelihood(without_missing, P2, emissions, initial)
        )

    def test_composite_is_sum_not_independence_claim(self, model):
        transitions, emissions, initial = model
        d1 = np.array([[0, 0], [1, 0]])
        d2 = np.array([[0, 0], [0, 1]])
        expected = sum(
            forward_log_likelihood(d, transitions, emissions, initial) for d in (d1, d2)
        )
        assert composite_log_likelihood(
            [d1, d2], transitions, emissions, initial
        ) == pytest.approx(expected)


class TestCleanSplitSupport:
    def test_no_cross_population_coalescence_before_split(self):
        for t in [0, 0.2, 1.0]:
            assert cross_population_survival(t, 1.0, lambda _: 2.0) == 1.0

    def test_ancestral_exponential_tail(self):
        split = 1.0
        rate = 0.5
        for t in [1.0, 1.5, 3.0]:
            expected = np.exp(-rate * max(t - split, 0))
            assert cross_population_survival(t, split, lambda _: rate) == pytest.approx(
                expected
            )
