"""Bounded, source-checked mechanisms from CLUES2.

This module is not CLUES2. It isolates the frequency grid, backward transition,
ancient-sample and coalescent emissions, log-space HMM recursion, importance
ratio aggregation, and likelihood-ratio convention used by CLUES2 commit
``b20dc5d``. Input conversion, ARG processing, epoch management, optimization,
and Monte Carlo trajectory integration remain the original software's job.
"""

from __future__ import annotations

from math import log

import numpy as np
from scipy.optimize import minimize_scalar
from scipy.special import logsumexp
from scipy.stats import beta, chi2, norm


def internal_diploid_size(n_haploid: float) -> float:
    """Apply CLUES2's public haploid-N to internal diploid-Ne conversion."""

    if not np.isfinite(n_haploid) or n_haploid <= 0:
        raise ValueError("haploid population size must be finite and positive")
    return n_haploid / 2.0


def backward_mean(x: float, s: float, h: float = 0.5) -> float:
    """Return CLUES2's one-generation backward normal-approximation mean."""

    if not 0 <= x <= 1:
        raise ValueError("frequency must be in [0, 1]")
    numerator = s * (x - 1.0) * x * (-x + h * (-1.0 + 2.0 * x))
    denominator = -1.0 + s * (2.0 * h * (x - 1.0) - x) * x
    if denominator == 0:
        raise ValueError("selection parameters make the backward mean singular")
    return float(x + numerator / denominator)


def backward_std(x: float, n_haploid: float) -> float:
    """Return the paper/public-API standard deviation, sqrt(x(1-x)/N)."""

    if not 0 <= x <= 1:
        raise ValueError("frequency must be in [0, 1]")
    internal = internal_diploid_size(n_haploid)
    return float(np.sqrt(x * (1.0 - x) / (2.0 * internal)))


def build_frequency_bins(k: int = 450) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Construct CLUES2's Beta(1/2, 1/2)-quantile frequency grid."""

    if k < 3:
        raise ValueError("at least three frequency bins are required")
    frequencies = beta.ppf(np.linspace(0.0, 1.0, k), 0.5, 0.5)
    safe = frequencies.copy()
    safe[0], safe[-1] = 1e-12, 1.0 - 1e-12
    log_frequencies = np.log(safe)
    log_complements = np.log1p(-safe)
    frequencies[0], frequencies[-1] = 0.0, 1.0
    return frequencies, log_frequencies, log_complements


def build_normal_cdf_lookup(
    n_points: int = 2000,
) -> tuple[np.ndarray, np.ndarray]:
    """Construct the normal-CDF interpolation table generated by CLUES2."""

    if n_points < 3:
        raise ValueError("at least three lookup points are required")
    probability = np.linspace(0.0, 1.0, n_points)
    probability[0], probability[-1] = 1e-10, 1.0 - 1e-10
    z = norm.ppf(probability)
    return z, norm.cdf(z)


def fast_normal_cdf(
    x: float,
    mean: float,
    standard_deviation: float,
    z_bins: np.ndarray,
    z_cdf: np.ndarray,
) -> float:
    """Interpolate the normal CDF using CLUES2's lookup convention."""

    if standard_deviation <= 0:
        raise ValueError("standard deviation must be positive")
    return float(np.interp((x - mean) / standard_deviation, z_bins, z_cdf))


def build_transition_matrix(
    frequencies: np.ndarray,
    n_haploid: float,
    s: float,
    h: float = 0.5,
    *,
    z_bins: np.ndarray | None = None,
    z_cdf: np.ndarray | None = None,
) -> np.ndarray:
    """Build CLUES2's sparse one-generation backward log transition matrix.

    ``n_haploid`` follows the documented command-line convention. The original
    program divides this value by two before its internal kernel; doing so makes
    the kernel variance ``x(1-x)/(2*N_diploid) = x(1-x)/N_haploid``.
    """

    frequencies = np.asarray(frequencies, dtype=float)
    if frequencies.ndim != 1 or len(frequencies) < 3:
        raise ValueError("frequencies must be a one-dimensional grid")
    if frequencies[0] != 0 or frequencies[-1] != 1 or np.any(np.diff(frequencies) <= 0):
        raise ValueError("grid must increase strictly from 0 to 1")
    internal_diploid_size(n_haploid)
    if z_bins is None or z_cdf is None:
        z_bins, z_cdf = build_normal_cdf_lookup()
    midpoints = (frequencies[:-1] + frequencies[1:]) / 2.0
    k = len(frequencies)
    matrix = np.full((k, k), -np.inf)
    matrix[0, 0] = matrix[-1, -1] = 0.0
    for i in range(1, k - 1):
        x = frequencies[i]
        mean = backward_mean(x, s, h)
        sd = backward_std(x, n_haploid)
        lower = max(int(np.argmin(np.abs(frequencies - (mean - 3.3 * sd)))) - 1, 0)
        upper = min(int(np.argmin(np.abs(frequencies - (mean + 3.3 * sd)))) + 1, k)
        probability = np.zeros(k)
        for j in range(lower, upper):
            if j == 0:
                probability[j] = fast_normal_cdf(midpoints[0], mean, sd, z_bins, z_cdf)
            elif j == k - 1:
                probability[j] = 1.0 - fast_normal_cdf(
                    midpoints[-1], mean, sd, z_bins, z_cdf
                )
            else:
                probability[j] = fast_normal_cdf(
                    midpoints[j], mean, sd, z_bins, z_cdf
                ) - fast_normal_cdf(midpoints[j - 1], mean, sd, z_bins, z_cdf)
        total = probability.sum()
        if total <= 0:
            raise FloatingPointError("transition row has no retained probability")
        probability /= total
        positive = probability > 0
        matrix[i, positive] = np.log(probability[positive])
    return matrix


def build_transition_matrix_fast(
    frequencies: np.ndarray,
    n_haploid: float,
    s: float,
    z_bins: np.ndarray,
    z_cdf: np.ndarray,
    h: float = 0.5,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Compatibility wrapper returning the matrix and its nonzero row bands."""

    matrix = build_transition_matrix(
        frequencies, n_haploid, s, h, z_bins=z_bins, z_cdf=z_cdf
    )
    lower = np.zeros(len(frequencies), dtype=int)
    upper = np.zeros(len(frequencies), dtype=int)
    for i, row in enumerate(matrix):
        finite = np.flatnonzero(np.isfinite(row))
        lower[i], upper[i] = finite[0], finite[-1] + 1
    return matrix, lower, upper


def log_coalescent_density(
    coal_times: np.ndarray,
    n_lineages: int,
    epoch_start: float,
    epoch_end: float,
    frequency: float,
    n_haploid: float,
    ancestral: bool = False,
) -> float:
    """Return CLUES2's source-style coalescent emission.

    The source drops event-rate factors independent of allele frequency. Those
    constants cancel in likelihood ratios over selection, so this is an
    emission score rather than a normalized absolute time density.
    """

    if n_lineages < 0 or epoch_end < epoch_start:
        raise ValueError("invalid lineage count or epoch")
    times = np.asarray(coal_times, dtype=float)
    if np.any(np.diff(times) < 0) or np.any(times < epoch_start) or np.any(times > epoch_end):
        raise ValueError("coalescence times must be sorted within the epoch")
    if len(times) > max(0, n_lineages - 1):
        raise ValueError("too many coalescences for the lineage count")
    if n_lineages <= 1:
        return 0.0
    x = 1.0 - frequency if ancestral else frequency
    if not 0 <= x <= 1:
        raise ValueError("frequency must be in [0, 1]")
    if x == 0:
        return -1e20
    n_diploid = internal_diploid_size(n_haploid)
    score = 0.0
    previous = epoch_start
    k = n_lineages
    for event_time in times:
        rate_numerator = k * (k - 1) / 4.0
        score += -log(x) - rate_numerator * (event_time - previous) / (x * n_diploid)
        previous = float(event_time)
        k -= 1
    rate_numerator = k * (k - 1) / 4.0
    score += -rate_numerator * (epoch_end - previous) / (x * n_diploid)
    return float(score)


def genotype_likelihood_emission(
    log_likelihoods: np.ndarray, log_frequency: float, log_complement: float
) -> float:
    """Marginalize diploid log genotype likelihoods ordered AA, AD, DD."""

    values = np.asarray(log_likelihoods, dtype=float)
    if values.shape != (3,):
        raise ValueError("diploid genotype likelihoods must have length three")
    log_genotype_frequency = np.array([
        2.0 * log_complement,
        log(2.0) + log_frequency + log_complement,
        2.0 * log_frequency,
    ])
    return float(logsumexp(values + log_genotype_frequency))


def haplotype_likelihood_emission(
    log_likelihoods: np.ndarray, log_frequency: float, log_complement: float
) -> float:
    """Marginalize haploid log likelihoods ordered ancestral, derived."""

    values = np.asarray(log_likelihoods, dtype=float)
    if values.shape != (2,):
        raise ValueError("haplotype likelihoods must have length two")
    return float(logsumexp(values + [log_complement, log_frequency]))


def forward_log_hmm(
    log_initial: np.ndarray,
    log_transitions: np.ndarray,
    log_emissions: np.ndarray,
) -> tuple[float, np.ndarray]:
    """Run a normalized log-space HMM recursion for audit-sized fixtures."""

    initial = np.asarray(log_initial, dtype=float)
    transitions = np.asarray(log_transitions, dtype=float)
    emissions = np.asarray(log_emissions, dtype=float)
    if transitions.shape != (len(initial), len(initial)):
        raise ValueError("transition matrix has incompatible shape")
    if emissions.ndim != 2 or emissions.shape[1] != len(initial):
        raise ValueError("emission matrix has incompatible shape")
    alpha = initial + emissions[0]
    scales = [float(logsumexp(alpha))]
    alpha -= scales[-1]
    history = [alpha.copy()]
    for emission in emissions[1:]:
        alpha = emission + logsumexp(alpha[:, None] + transitions, axis=0)
        scales.append(float(logsumexp(alpha)))
        alpha -= scales[-1]
        history.append(alpha.copy())
    return float(sum(scales)), np.asarray(history)


def importance_log_likelihood_ratio(
    selected_tree_log_likelihoods: np.ndarray,
    neutral_tree_log_likelihoods: np.ndarray,
) -> float:
    """Aggregate CLUES2 tree-sample log likelihood ratios with log-mean-exp."""

    selected = np.asarray(selected_tree_log_likelihoods, dtype=float)
    neutral = np.asarray(neutral_tree_log_likelihoods, dtype=float)
    if selected.shape != neutral.shape or selected.ndim != 1 or len(selected) == 0:
        raise ValueError("selected and neutral arrays must be nonempty and aligned")
    return float(logsumexp(selected - neutral) - np.log(len(selected)))


def likelihood_ratio_test(
    log_likelihood_selected: float,
    log_likelihood_neutral: float,
    df: int = 1,
) -> tuple[float, float, float]:
    """Return 2*Delta-logL, chi-square tail probability, and -log10(p)."""

    if df < 1:
        raise ValueError("degrees of freedom must be positive")
    statistic = max(0.0, 2.0 * (log_likelihood_selected - log_likelihood_neutral))
    log_p = float(chi2.logsf(statistic, df))
    return statistic, float(np.exp(log_p)), float(-log_p / np.log(10.0))


def estimate_selection_single(negative_log_likelihood, s_max: float = 0.1):
    """Bounded teaching optimizer; CLUES2 itself uses bracketed Brent retries."""

    result = minimize_scalar(
        negative_log_likelihood, bounds=(-s_max, s_max), method="bounded"
    )
    return float(result.x), float(result.fun)


def compute_trajectory_summary(
    posterior: np.ndarray, frequencies: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return posterior mean and equal-tail 95% interval at each time."""

    posterior = np.asarray(posterior, dtype=float)
    frequencies = np.asarray(frequencies, dtype=float)
    if posterior.ndim != 2 or posterior.shape[0] != len(frequencies):
        raise ValueError("posterior rows must correspond to frequency bins")
    totals = posterior.sum(axis=0)
    if np.any(totals <= 0):
        raise ValueError("posterior columns must have positive mass")
    normalized = posterior / totals
    mean = frequencies @ normalized
    cumulative = np.cumsum(normalized, axis=0)
    lower = np.array([frequencies[np.searchsorted(cumulative[:, t], 0.025)]
                      for t in range(posterior.shape[1])])
    upper = np.array([frequencies[np.searchsorted(cumulative[:, t], 0.975)]
                      for t in range(posterior.shape[1])])
    return mean, lower, upper


def demo() -> None:
    """Print the pinned nine-bin source fixture used by the tests."""

    frequencies, _, _ = build_frequency_bins(9)
    transition = build_transition_matrix(frequencies, 200.0, 0.02)
    print("middle transition row:")
    print(np.exp(transition[4]))


if __name__ == "__main__":
    demo()
